name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    concurrency: deploy-group

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Chromium dependencies
        run: sudo apt-get install -y libappindicator3-1 fonts-liberation

      # Backend setup
      #- name: Install backend dependencies
      #  run: npm install

      #- name: Run backend tests
      #  run: npm test

      # Frontend setup
      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend

      - name: Build frontend
        run: npm run build
        working-directory: frontend

      - name: Run frontend tests in headless mode
        run: |
          npm test --include=frontend/src/app/app.component.spec.ts --include=frontend/src/app/guards/auth.guard.spec.ts --include=frontend/src/app/guards/redirect.guard.spec.ts --include=frontend/src/app/password-change-modal/password-change-modal.component.spec.ts --include=frontend/src/app/library-list/library-list.component.spec.ts --include=frontend/src/app/login/login.component.spec.ts --include=frontend/src/app/my-account/my-account.component.spec.ts --include=frontend/src/app/create-library-item/create-library-item.component.spec.ts --include=frontend/src/app/menu-bar/menu-bar.component.spec.ts --include=frontend/src/app/main-layout/main-layout.component.spec.ts --include=frontend/src/app/my-borrowed-items/my-borrowed-items.component.spec.ts --include=frontend/src/app/create-user/create-user.component.spec.ts --include=frontend/src/app/user-management/user-management.component.spec.ts --include=frontend/src/app/services/user.service.spec.ts --include=frontend/src/app/services/library.service.spec.ts --include=frontend/src/app/services/borrow.service.spec.ts --include=frontend/src/app/services/logout.service.spec.ts -- --watch=false --browsers=ChromeHeadless
        working-directory: frontend
